### ISSUE TITLE
If FlipYAxis is true, the angle is also reversed.

### ISSUE THREAD

**Issue by setanarut** [demouth/ebiten-chipmunk#1]
https://github.com/demouth/ebiten-chipmunk/blob/e7163fe98b753d8ca21043ff91014ea3acd4b4f1/ebitencp.go#L57

### To fix it, you need to reverse the angle like this.

```Go
func (d *Drawer) DrawCircle(pos cp.Vector, angle, radius float64, outline, fill cp.FColor, data interface{}) {
	var f float64 = 1
	if d.FlipYAxis {
		f = -1
                angle *= f // flip angle
	}
```

(Also, everything is aligned to the center of the screen, which is a separate topic)

**Comment by demouth** [comment]
@setanarut Thank you for reporting this issue.
I've made the necessary changes to fix this problem.

**Comment by setanarut** [comment]
You're welcome, I also set FlipYAxis to default and removed screen centering. I update the coordinates of the examples according to Ebitengine, here's an example 

https://github.com/setanarut/ebitencm/blob/solust/examples%2Fbasic%2Fmain.go
