### ISSUE TITLE
Camera proposal

### ISSUE THREAD

**Issue by setanarut** [demouth/ebiten-chipmunk#2]
Maybe you want to implement my solution for rotation and scaling (camera zoom) in your package.

vertices transform
https://github.com/setanarut/ebitencm/blob/88eaf86e5af6745ca695a39513490db4e2776379/ebitencm.go#L247

Cursor transform
https://github.com/setanarut/ebitencm/blob/88eaf86e5af6745ca695a39513490db4e2776379/grab.go#L55

### Camera demo

Run camera example on your local machine

```
go run github.com/setanarut/ebitencm/examples/theojansen_cam@latest
```

- Camera Position = WASD
- Camera Rotation = Q / E
- Camera Zoom = Z / X
- Drag object = Cursor
- Reset camera = Backspace

**Comment by demouth** [comment]
Hi @setanarut ,

I wanted to let you know that I’ve created a PR (#3) that implements the proposal you submitted in this issue. Feel free to take a look and share any feedback you might have!

Thanks again for your suggestion!

**Comment by setanarut** [comment]
@demouth unused parameter `size` -> https://github.com/demouth/ebitencp/blob/b81bea06b68e6cfd9f35db81855ca68d5f959233/ebitencp.go#L230
